apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-demo
  namespace: chaos-testing
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  mode: all
  stressors:
    cpu:
      workers: 2
      load: 75
      options: ["--cpu-method=all"]
  duration: "3m" 