apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-demo
  namespace: chaos-testing
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  mode: all
  stressors:
    memory:
      workers: 2
      size: "256MB"
  duration: "2m" 