apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-demo
  namespace: chaos-testing
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  mode: all
  action: delay
  duration: "30s"
  delay:
    latency: "200ms"
    correlation: "25"
    jitter: "50ms"
  direction: to
  target:
    selector:
      namespaces:
        - default
    mode: all 