apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-example
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  stressors:
    memory:
      workers: 1
      size: "256MB"
      options: ["--vm 1", "--vm-bytes 256M", "--timeout 60s"]
  duration: "1m" 