apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app  # Target the resilient-app we were testing
  duration: "30s"
  scheduler:
    cron: "@every 5m"  # Run every 5 minutes
  # Pause the experiment after 10 iterations
  paused: false
  containerNames: [""]  # Apply to all containers in the pod 