apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: secret-rotation-test
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
      secrets: "true"  # Target only pods that use secrets
  scheduler:
    cron: "@every 2m"  # Rotate secrets every 2 minutes
  duration: "5m" 