apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-chaos
  namespace: chaos-testing
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  volumePath: /
  path: "*"
  delay: "100ms"
  percent: 50
  duration: "60s" 