apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-chaos
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: resilient-app
  delay:
    latency: "200ms"
    correlation: "25"
    jitter: "50ms"
  duration: "60s"
  direction: to
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app: resilient-app
    mode: one 